/**
 * Image & Visual Asset Generation Tools
 * 
 * Equips the AI agent with visual generation capabilities: creating vector SVG assets,
 * UI mockups, architectural diagrams, and analyzing workspace images.
 */

import path from "path";
import { registerTool } from "./index.js";
import { workspaceService } from "../services/workspaceService.js";
import { permissionEngine } from "../services/permissionEngine.js";

export function registerImageTools() {
  // 1. generate_image
  registerTool(
    {
      type: "function",
      function: {
        name: "generate_image",
        description:
          "Generate an image, visual mockup, SVG diagram, or graphic asset and save it into workspace/assets/. " +
          "Supports direct SVG vector code generation or AI visual asset generation.",
        parameters: {
          type: "object",
          properties: {
            prompt: {
              type: "string",
              description: "Detailed description of the visual asset or illustration",
            },
            filename: {
              type: "string",
              description: "Target filename inside assets/ (e.g. 'architecture.svg', 'logo.svg', 'banner.svg')",
            },
            svg_content: {
              type: "string",
              description: "Complete, valid SVG XML code if generating vector graphics or UI diagrams",
            },
            image_url: {
              type: "string",
              description: "Optional external image URL if embedding a remote asset",
            },
          },
          required: ["prompt", "filename"],
        },
      },
    },
    async (args, ctx = {}) => {
      // Permission Check
      const perm = await permissionEngine.checkPermission({
        resource: "file",
        action: "write",
        payload: args,
        turnId: ctx.turnId,
        sessionId: ctx.sessionId,
      });
      if (!perm.granted) return { success: false, error: perm.reason };

      const safeName = args.filename.replace(/[^a-zA-Z0-9._-]/g, "_");
      const relativePath = path.posix.join("assets", safeName);

      try {
        let fileContent = args.svg_content;

        if (!fileContent && !args.image_url) {
          // If no raw SVG provided, generate a clean responsive placeholder SVG
          const title = args.prompt.slice(0, 40).replace(/&/g, "&amp;").replace(/</g, "&lt;");
          fileContent = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 800 500" width="100%" height="100%">
  <defs>
    <linearGradient id="grad" x1="0%" y1="0%" x2="100%" y2="100%">
      <stop offset="0%" stop-color="#4f46e5" />
      <stop offset="100%" stop-color="#06b6d4" />
    </linearGradient>
    <filter id="glow">
      <feGaussianBlur stdDeviation="6" result="coloredBlur"/>
      <feMerge>
        <feMergeNode in="coloredBlur"/>
        <feMergeNode in="SourceGraphic"/>
      </feMerge>
    </filter>
  </defs>
  <rect width="100%" height="100%" fill="#0f172a" rx="16"/>
  <rect x="20" y="20" width="760" height="460" fill="none" stroke="url(#grad)" stroke-width="2" rx="12" stroke-dasharray="8 8"/>
  <circle cx="400" cy="220" r="70" fill="url(#grad)" opacity="0.15" filter="url(#glow)"/>
  <circle cx="400" cy="220" r="45" fill="none" stroke="url(#grad)" stroke-width="3"/>
  <text x="400" y="228" font-family="system-ui, sans-serif" font-size="28" font-weight="bold" fill="#ffffff" text-anchor="middle">ATH</text>
  <text x="400" y="340" font-family="system-ui, sans-serif" font-size="20" font-weight="600" fill="#f8fafc" text-anchor="middle">${title}</text>
  <text x="400" y="375" font-family="system-ui, sans-serif" font-size="14" fill="#94a3b8" text-anchor="middle">Generated by Autonomous AI Studio</text>
</svg>`;
        }

        if (fileContent) {
          await workspaceService.writeFile(relativePath, fileContent, {
            source: "agent",
            actor: "agent",
            turnId: ctx.turnId,
            operationId: ctx.operationId,
          });

          return {
            success: true,
            output: `Visual asset created at ${relativePath}\n\n![${args.prompt}](${relativePath})`,
            assetPath: relativePath,
          };
        }

        return {
          success: true,
          output: `Image reference saved: ![${args.prompt}](${args.image_url})`,
          assetUrl: args.image_url,
        };
      } catch (err) {
        return { success: false, error: err.message };
      }
    }
  );

  // 2. analyze_image
  registerTool(
    {
      type: "function",
      function: {
        name: "analyze_image",
        description: "Analyze an image or graphic asset in the workspace to retrieve file metadata.",
        parameters: {
          type: "object",
          properties: {
            path: { type: "string", description: "Relative path to image file in workspace" },
          },
          required: ["path"],
        },
      },
    },
    async (args) => {
      try {
        const file = await workspaceService.readFile(args.path);
        const ext = path.extname(args.path).toLowerCase();
        return {
          success: true,
          output: `Image: ${file.path} (${(file.size / 1024).toFixed(1)} KB, format: ${ext || "unknown"})`,
          metadata: { path: file.path, size: file.size, extension: ext },
        };
      } catch (err) {
        return { success: false, error: err.message };
      }
    }
  );
}
